app/blueprints/posts/models.py
import datetime
from app import db
from app.constants import PostStatus
from slugify import slugify


class Post(db.Model):
    __tablename__ = "posts"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    updated_at = db.Column(db.DateTime, nullable=False)
    status = db.Column(db.Enum(PostStatus), nullable=False, default=PostStatus.DRAFT)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f"<Post {self.title}>"

app/blueprints/users/models.py
from datetime import datetime
from app import db
from app.constants import UserType
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(255), nullable=False)
    nickname = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    _password_hash = db.Column(db.String(255), nullable=False)
    user_type = db.Column(db.Enum(UserType), nullable=False, default=UserType.READER)
    is_email_confirmed = db.Column(db.Boolean, nullable=False, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"<User {self.email}>"

    @property
    def password(self):
        raise AttributeError('Password is not a readable attribute')

    @password.setter
    def password(self, password):
        self._password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self._password_hash, password)

app/blueprints/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length
from app.constants import PostStatus


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, max=50)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min=3, max=500)])
    status = SelectField('Status', choices=[status.value for status in PostStatus if status != PostStatus.DELETED], default=PostStatus.DRAFT.value)
    slug = StringField('Slug', validators=[DataRequired(), Length(min=3, max=255)])
    submit = SubmitField('Create')

app/__init__.py
import os

from flask import Flask
from flask_smorest import Api
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


BASE_DIR = os.path.abspath(os.path.dirname(__file__))

db = SQLAlchemy()

login_manager = LoginManager()


def create_app():
    app = Flask(__name__)

    app.config.from_envvar('YOURAPPLICATION_SETTINGS')

    from .blueprints.main.error_handler import page_not_found
    app.register_error_handler(404, page_not_found)

    api = Api(app)

    from app.blueprints import (UsersBlueprint,
                                PostsBlueprint,
                                AuthBlueprint,
                                MainBlueprint)

    api.register_blueprint(MainBlueprint)
    api.register_blueprint(UsersBlueprint)
    api.register_blueprint(PostsBlueprint)
    api.register_blueprint(AuthBlueprint)

    login_manager.init_app(app)
    login_manager.login_view = 'auth.sign-in'

    db.init_app(app)
    Migrate(app, db)

    return app

app/blueprints/__init__.py
from .main import MainBlueprint

from .users import UsersBlueprint
from .users.models import User


from .posts import PostsBlueprint
from .posts.models import Post

from .auth import AuthBlueprint

app/blueprints/main/__init__.py
from flask_smorest import Blueprint

MainBlueprint = Blueprint(
    'main',
    __name__,
    url_prefix='/',
    description='Main routes'
)

from . import routes

app/blueprints/main/routes.py
from .views import home, about
from . import MainBlueprint


MainBlueprint.add_url_rule("/", "home", home, methods=["GET"])
MainBlueprint.add_url_rule("/about", "about", about, methods=["GET"])

app/blueprints/main/views.py
from flask import render_template


def home():
    return render_template('main/home.html', title='Home')


def about():
    return render_template('main/about.html', title='About')

app/blueprints/posts/__init__.py
from flask_smorest import Blueprint
from .models import Post

PostsBlueprint = Blueprint('posts', __name__, url_prefix='/posts', description='Posts Operations')

from . import routes

app/blueprints/posts/routes.py
from . import PostsBlueprint
from .views import posts, blog, post_create


# --------------- POSTS ---------------
PostsBlueprint.add_url_rule("/posts", "posts", posts, methods=["GET"])


# --------------- BLOG ---------------
PostsBlueprint.add_url_rule("/blog", "blog", blog, methods=["GET"])
PostsBlueprint.add_url_rule("/blog/create", "post-create", post_create, methods=["GET", "POST"])

app/blueprints/posts/views.py
from flask import render_template, flash, url_for
from .forms import PostForm
from flask_login import login_user, logout_user, login_required, current_user


def posts():
    return render_template('posts/posts.html', title='Posts')


@login_required
def blog():
    return render_template('posts/blog.html', title='Blog')


@login_required
def post_create():
    form = PostForm()
    post_created = False
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        status = form.status.data
        post_created = True
        flash('Post Create Success! You can see it in the blog page.')

    return render_template('posts/post_create.html', title='Create Post', form=form, post_created=post_created)

app/blueprints/users/__init__.py
from flask_smorest import Blueprint

UsersBlueprint = Blueprint('users', __name__, url_prefix='/users', description='Users API')

from .models import User

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/main.css') }}">

    {% block stylesheet %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}
{% include "main/nav_header.html" %}
{% endblock %}
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous">
</script>
</body>
</html>

app/templates/main/about.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
{{ super() }}
    <h1>About Page</h1>
{% endblock %}

app/templates/main/home.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
  {{ super() }}
  <h1>Home Page</h1>
{% endblock %}

app/templates/main/nav_header.html
  <nav class="navMenu">
    <a href="{{ url_for('main.home') }}" class="logo">TinyTales</a>
      <div class="menu">
        <input type="text" placeholder="Search..." class="search-input">
        <button class="search-button">Search</button>
        <a href="{{ url_for('main.home') }}">Home</a>
        <a href="{{ url_for('posts.posts') }}">Posts</a>
        <a href="{{ url_for('posts.blog') }}">Blog</a>
        <a href="{{ url_for('main.about') }}">About</a>
        {% if current_user.is_authenticated %}
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
          <a href="{{ url_for('auth.sign-in') }}">Sign in</a>
          <a href="{{ url_for('auth.sign-up') }}">Sing up</a>
        {% endif %}
      </div>
  </nav>

app/templates/posts/blog.html
{% extends "base.html" %}

{% block stylesheet %}

{% endblock %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
{{ super() }}
<div class="my-blog-header">
    <p class="my-blog">My blog</p>
    <a href="{{ url_for('posts.post-create') }}" class="btn btn-outline-light btn-lg" role="button">Create Post</a>
</div>
{% endblock %}

app/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}
c
{% block content %}
{{ super() }}
<div class="post-create-container">
    <p class="create-post-p">Create Post</p>
    <form class="post-create-form" method="post">
        {% if not post_created %}
            {{ form.hidden_tag() }}
            {{ form.title(placeholder="Title", class="form-control", id="floatingInput") }}
            {{ form.content(placeholder="Content", class="form-control", id="floatingTextarea2", style="height: 400px") }}
            {{ form.status(class="form-select") }}
            {{ form.submit(class="btn btn-outline-light btn-lg") }}
        {% else %}
            {% for message in get_flashed_messages() %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                    <a href="{{ url_for('posts.blog') }}" class="alert-link"> Go Blog</a>
                </div>
            {% endfor %}
        {% endif %}

    </form>
</div>
{% endblock %}

app/templates/posts/posts.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
{{ super() }}
<h1>There is posts block</h1>
{% endblock %}